config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do

  devise_for :users, path_prefix: "devise", controllers: { registrations: "registrations" }
  get "/logout" => "sessions#destroy", :as => :logout
  devise_scope :user do
    scope "my" do
      put "profile/update", to: "registrations#update"
      put "password/update", to: "registrations#update_password"
    end
  end

  authenticate :user, ->(u) { u.super_admin? } do
    mount Sidekiq::Web, at: "/sidekiq"

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: "users#index"
      resources :users
    end
  end

  authenticate :user, ->(u) { !u.super_admin? } do
    get "/active_admin" => redirect("/")
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "login" => "sessions#create", as: "login"
        delete "logout" => "sessions#destroy", as: "logout"
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
      resources :notes, only: [:index, :create, :destroy] do
        member do
          put 'move_task'
        end
        collection do
          post 'bulk_delete'
        end
      end
      resources :tags, only: [:index, :create, :destroy] do
        collection do
          post 'bulk_delete'
        end
      end
    end
  end

  root "home#index"
  get '*path', to: 'home#index', via: :all
end

app/views/shared/header/_tabs.html.slim
.header.bg-white.border-b.shadow-sm.py-4.mb-6
  .container.mx-auto.flex.flex-grow-1.px-4
    = link_to 'Wheel', root_path, class: 'text-2xl font-semibold hover:text-teal-600'

    - navLinkStyle = 'nav-link text-base text-gray-800 ml-6 hover:text-teal-600'

    .flex.ml-auto.items-center
      .nav-item
        = link_to 'Features', '/features', class: navLinkStyle
      .nav-item
        = link_to 'Contact', '/contact', class: navLinkStyle

      - if user_signed_in?
          = render 'shared/header/user_is_signed_in'
      - else
        .nav-item
          = link_to 'Sign In', new_session_path(:user), class: navLinkStyle

app/views/shared/header/_user_is_signed_in.html.slim
- navLinkStyle = 'nav-link text-base text-gray-800 flex items-center hover:text-teal-600 focus:outline-none'
- drodownLinkStyle = 'rounded-t hover:bg-gray-200 hover:text-gray-800 py-2 px-4 block whitespace-no-wrap'

div class="dropdown inline-block relative ml-6"
  button class=navLinkStyle data-behavior="dropdown-toggle"
    .mr-1 = current_user.name
    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/> </svg>

  div data-behavior="dropdown-menu" class="overflow-hidden hidden"
    .dropdown-overlay  class="bg-transparent top-0 left-0 w-full h-full fixed z-10" data-behavior="dropdown-toggle"
    ul class="dropdown-menu bg-white shadow-md border absolute right-0 text-gray-700 pt-1 mt-2 rounded-md z-20"
      - if super_admin_signed_in?
        li
          = link_to 'Active Admin', active_admin_root_path, class: drodownLinkStyle
        li
          = link_to 'Sidekiq', sidekiq_web_path, "target" => '_blank', class: drodownLinkStyle
      li
        = link_to 'My Account', profile_path, class: drodownLinkStyle
      li
        = link_to 'Change Password', password_edit_path, class: drodownLinkStyle
      li
        = link_to 'Logout', logout_path, class: drodownLinkStyle