config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do

  devise_for :users, path_prefix: "devise", controllers: { registrations: "registrations" }
  get "/logout" => "sessions#destroy", :as => :logout
  devise_scope :user do
    scope "my" do
      put "profile/update", to: "registrations#update"
      put "password/update", to: "registrations#update_password"
    end
  end

  authenticate :user, ->(u) { u.super_admin? } do
    mount Sidekiq::Web, at: "/sidekiq"

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: "users#index"
      resources :users
    end
  end

  authenticate :user, ->(u) { !u.super_admin? } do
    get "/active_admin" => redirect("/")
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "login" => "sessions#create", as: "login"
        delete "logout" => "sessions#destroy", as: "logout"
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
      resources :notes, only: [:index, :create, :destroy] do
        member do
          put 'move_task'
        end
        collection do
          post 'bulk_delete'
        end
      end
      resources :tags, only: [:index, :create, :destroy] do
        collection do
          post 'bulk_delete'
        end
      end
    end
  end

  root "home#index"
  get '*path', to: 'home#index', via: :all
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, :rememberable

  has_many :tags, dependent:  :delete_all
  has_many :notes, dependent: :delete_all

  before_save :ensure_authentication_token_is_present

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def name
    [first_name, last_name].join(" ").strip
  end

  def super_admin?
    role == "super_admin"
  end

  def as_json(options = {})
    new_options = options.merge(only: [:email, :first_name, :last_name, :current_sign_in_at])

    super new_options
  end

  private

    def send_devise_notification(notification, *args)
      devise_mailer.send(notification, self, *args).deliver_later(queue: "devise_email")
    end

    def ensure_authentication_token_is_present
      if authentication_token.blank?
        self.authentication_token = generate_authentication_token
      end
    end

    def generate_authentication_token
      loop do
        token = Devise.friendly_token
        break token unless User.where(authentication_token: token).first
      end
    end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::BaseController
  skip_before_action :authenticate_user!, only: [:create]
  skip_before_action :authenticate_user_using_x_auth_token, only: [:create]

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    if @user
      render json: @user
    else
      respond_with_error "User with id #{params[:id]} not found.", :not_found
    end
  end

  def create
    user = User.create user_params

    if user.valid?
      sign_in(user)
      render json: { user: user, auth_token: user.authentication_token }
    else
      render json: { error: user.errors.full_messages.to_sentence }, status: 422
    end
  end

  def update
    if @user.blank?
      respond_with_error "User with id #{params[:id]} not found.", :not_found

    elsif @user.update(user_params)
      render json: @user

    else
      render json: { error: @user.errors.full_messages.to_sentence }, status: 422
    end
  end

  def destroy
    if @user.blank?
      respond_with_error "User with id #{params[:id]} not found.", :not_found

    elsif @user.destroy
      render json: @user

    else
      render json: { error: @user.errors.full_messages.to_sentence }, status: 422
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
    end
end

app/views/users/shared/_links.html.slim
- linksWrapper = "mt-2 text-center"
- linkStyle = "block text-teal-600 hover:text-black mt-2"

div class=linksWrapper
  - if controller_name != 'sessions'
    = link_to "Sign in instead", new_session_path(resource_name), class: linkStyle
  
  - if devise_mapping.registerable? && controller_name != 'registrations'
    = link_to "Signup", new_registration_path(resource_name), class: linkStyle

  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    = link_to "Forgot password?", new_password_path(resource_name), class: linkStyle

  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: linkStyle
  
  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: linkStyle
  
  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), class: linkStyle